using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("AbilityThrottleTests")]
[assembly: InternalsVisibleTo("MainWindowNavigationTests")]
[assembly: InternalsVisibleTo("CombatRecorderTests")]
[assembly: InternalsVisibleTo("EventSystemTests")]
[assembly: InternalsVisibleTo("CombatRecorderViewerTests")]
[assembly: InternalsVisibleTo("GameEventHookTests")]
[assembly: InternalsVisibleTo("SpellCastCallbackTests")]
[assembly: InternalsVisibleTo("GCDHelperTests")]
[assembly: InternalsVisibleTo("CombatCommandTests")]
[assembly: InternalsVisibleTo("OverlayVisibilityTests")]
[assembly: InternalsVisibleTo("MovementLogicTests")]
[assembly: InternalsVisibleTo("MovementQueueTests")]
[assembly: InternalsVisibleTo("PauseGateTests")]
[assembly: InternalsVisibleTo("CountdownStartTests")]
[assembly: InternalsVisibleTo("CountdownFlowTests")]
[assembly: InternalsVisibleTo("AcrRuntimeChainTests")]
